source "$HOME/.cargo/env"

# default editor is nvim
export EDITOR='nvim'
export LANG="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"
export LC_CTYPE="en_US.UTF-8"

export GOPATH=$HOME

# Add libraries path to linker
export LD_LIBRARY_PATH="/usr/local/lib"

export PATH="$HOME/.local/bin:$PATH"
export PATH="$HOME/.cargo/bin:$PATH"
export PATH="$HOME/bin:$PATH"
export PATH="$HOME/bin/go:$PATH"
export PATH="$HOME/scripts/enabled/:$PATH"

export XDG_CONFIG_HOME=$HOME/.config

# change man pager to nvim
export MANPAGER="nvim -c 'set ft=man' -"

# allow to edit commands in editor
autoload -z edit-command-line
zle -N edit-command-line
bindkey "^X^E" edit-command-line

alias vim=nvim

# add fzf bindings
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# init pyenv
if [ -d "$HOME/.pyenv/bin" ]
then
    export PATH="$HOME/.pyenv/bin:$PATH"
    eval "$(pyenv init -)"
    eval "$(pyenv virtualenv-init -)"
fi

# switch keyboard layouts with alt+space
setxkbmap -layout us,ru -option 'grp:alt_space_toggle'
