SCRIPT_DIR=$(realpath $(dirname $0))

zstyle ':completion:*' completer _complete _ignored _approximate
zstyle :compinstall filename '/home/nk2ge5k/.zshrc'

autoload -Uz compinit
for dump in ~/.zcompdump(N.mh+24); do
    echo "Compimit"
    compinit
done
compinit -C

autoload -U colors && colors
PS1="%{$fg[blue]%}%m %{$fg[yellow]%}%(4~|%3~|%~)%{$reset_color%}$ "

source $SCRIPT_DIR/env.zsh
source $SCRIPT_DIR/aliases.zsh
source $SCRIPT_DIR/history.zsh
source $SCRIPT_DIR/key-bindings.zsh

# init pyenv
pyenv() {
    echo "PYENV not loaded! Loading now..."
    unset -f pyenv

    export PYENV_ROOT="$HOME/.pyenv"
    if [ -d "$PYENV_ROOT" ]
    then
        export PATH="$PYENV_ROOT/bin:$PATH"
        eval "$(pyenv init -)"
        eval "$(pyenv virtualenv-init -)"
    fi
}

# init nvm
nvm() {
    echo "NVM not loaded! Loading now..."
    unset -f nvm

    export NVM_DIR="$HOME/.config/nvm"
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
    [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
}
