zstyle ':completion:*' completer _complete _ignored _approximate
zstyle :compinstall filename '/home/nk2ge5k/.zshrc'

autoload -Uz compinit

for dump in ~/.zcompdump(N.mh+24); do
    echo "Compimit"
    compinit
done

compinit -C

export HISTFILE=~/.zsh_history
export HISTSIZE=1000
export SAVEHIST=10000
setopt appendhistory

bindkey -v
# allow to edit commands in editor
autoload -z edit-command-line
zle -N edit-command-line
bindkey "^X^E" edit-command-line

autoload -U colors && colors
PS1="%{$fg[blue]%}%m %{$fg[yellow]%}%(4~|%3~|%~)%{$reset_color%}$ "

source "$HOME/.cargo/env"

# default editor is nvim
export EDITOR='nvim'
export LANG="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"
export LC_CTYPE="en_US.UTF-8"

export GOPATH=$HOME

# Add libraries path to linker
export LD_LIBRARY_PATH="/usr/local/lib"

export PATH="$HOME/.local/bin:$PATH"
export PATH="$HOME/.cargo/bin:$PATH"
export PATH="$HOME/bin:$PATH"
export PATH="$HOME/bin/go/bin:$PATH"
export PATH="$HOME/scripts/enabled/:$PATH"

export XDG_CONFIG_HOME=$HOME/.config

# change man pager to nvim
export MANPAGER="nvim -c 'set ft=man' -"

alias vim=nvim
alias ls='ls --color=auto'
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

alias grep='rg --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# init pyenv

export GPG_TTY=`tty`

pyenv() {
    echo "PYENV not loaded! Loading now..."
    unset -f pyenv

    export PYENV_ROOT="$HOME/.pyenv"
    if [ -d "$PYENV_ROOT" ]
    then
        export PATH="$PYENV_ROOT/bin:$PATH"
        eval "$(pyenv init -)"
        eval "$(pyenv virtualenv-init -)"
    fi
}

nvm() {
    echo "NVM not loaded! Loading now..."
    unset -f nvm

    export NVM_DIR="$HOME/.config/nvm"
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
    [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
}

profzsh() {
    shell=$(which zsh)
    ZPROF=true $shell -i -c exit
}
